/* ==========================================
   ANIMATIONS.JS
      The World of Ninin Anto
      ========================================== */

      document.addEventListener("DOMContentLoaded", () => {

          /* ==========================
                 Logo Parallax Effect
                     ========================== */

                         const logo = document.querySelector(".main-logo");

                             if (logo) {

                                     document.addEventListener("mousemove", (e) => {

                                                 const x = (window.innerWidth / 2 - e.clientX) / 60;
                                                             const y = (window.innerHeight / 2 - e.clientY) / 60;

                                                                         logo.style.transform =
                                                                                         `translate(${x}px, ${y}px)`;

                                                                                                 });

                                                                                                     }

                                                                                                         /* ==========================
                                                                                                                Card Hover Tilt
                                                                                                                    ========================== */

                                                                                                                        const cards = document.querySelectorAll(".card");

                                                                                                                            cards.forEach(card => {

                                                                                                                                    card.addEventListener("mousemove", (e) => {

                                                                                                                                                const rect = card.getBoundingClientRect();

                                                                                                                                                            const x = e.clientX - rect.left;
                                                                                                                                                                        const y = e.clientY - rect.top;

                                                                                                                                                                                    const rotateY =
                                                                                                                                                                                                    ((x / rect.width) - 0.5) * 12;

                                                                                                                                                                                                                const rotateX =
                                                                                                                                                                                                                                ((rect.height / 2 - y) / rect.height) * 12;

                                                                                                                                                                                                                                            card.style.transform =
                                                                                                                                                                                                                                                            `perspective(900px)
                                                                                                                                                                                                                                                                             rotateX(${rotateX}deg)
                                                                                                                                                                                                                                                                                              rotateY(${rotateY}deg)
                                                                                                                                                                                                                                                                                                               translateY(-10px)`;

                                                                                                                                                                                                                                                                                                                       });

                                                                                                                                                                                                                                                                                                                               card.addEventListener("mouseleave", () => {

                                                                                                                                                                                                                                                                                                                                           card.style.transform =
                                                                                                                                                                                                                                                                                                                                                           "perspective(900px) rotateX(0) rotateY(0) translateY(0)";

                                                                                                                                                                                                                                                                                                                                                                   });

                                                                                                                                                                                                                                                                                                                                                                       });

                                                                                                                                                                                                                                                                                                                                                                           /* ==========================
                                                                                                                                                                                                                                                                                                                                                                                  Gold Button Glow
                                                                                                                                                                                                                                                                                                                                                                                      ========================== */

                                                                                                                                                                                                                                                                                                                                                                                          const buttons = document.querySelectorAll(".gold-btn");

                                                                                                                                                                                                                                                                                                                                                                                              buttons.forEach(button => {

                                                                                                                                                                                                                                                                                                                                                                                                      button.addEventListener("mouseenter", () => {

                                                                                                                                                                                                                                                                                                                                                                                                                  button.style.boxShadow =
                                                                                                                                                                                                                                                                                                                                                                                                                                  "0 0 30px rgba(212,175,55,.6)";

                                                                                                                                                                                                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                                                                                                                                                                                                                  button.addEventListener("mouseleave", () => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                              button.style.boxShadow =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              "0 0 0 rgba(212,175,55,0)";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              /* ==========================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Smooth Fade for Sections
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ========================== */

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             const sections = document.querySelectorAll(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     "section"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             const observer = new IntersectionObserver((entries) => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     entries.forEach(entry => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 if (entry.isIntersecting) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 entry.target.style.opacity = "1";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 entry.target.style.transform = "translateY(0)";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }, {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 threshold:0.15

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         sections.forEach(section => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 section.style.opacity = "0";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         section.style.transform = "translateY(40px)";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 section.style.transition = "all .9s ease";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         observer.observe(section);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             });