/* ==========================================================
   THE WORLD OF NININ ANTO
      Version 2.0
         main.js
         ========================================================== */

         document.addEventListener("DOMContentLoaded", () => {

             /* ===========================
                    LOADER
                        =========================== */

                            const loader = document.querySelector(".loader");

                                window.addEventListener("load", () => {

                                        if(loader){

                                                    loader.classList.add("hide");

                                                            }

                                                                });


                                                                    /* ===========================
                                                                           MOBILE MENU
                                                                               =========================== */

                                                                                   const menuToggle = document.querySelector(".menu-toggle");

                                                                                       const navLinks = document.querySelector(".nav-links");

                                                                                           if(menuToggle && navLinks){

                                                                                                   menuToggle.addEventListener("click",()=>{

                                                                                                               navLinks.classList.toggle("active");

                                                                                                                       });

                                                                                                                               document.querySelectorAll(".nav-links a").forEach(link=>{

                                                                                                                                           link.addEventListener("click",()=>{

                                                                                                                                                           navLinks.classList.remove("active");

                                                                                                                                                                       });

                                                                                                                                                                               });

                                                                                                                                                                                   }


                                                                                                                                                                                       /* ===========================
                                                                                                                                                                                              STICKY NAVBAR
                                                                                                                                                                                                  =========================== */

                                                                                                                                                                                                      const navbar = document.querySelector(".navbar");

                                                                                                                                                                                                          window.addEventListener("scroll",()=>{

                                                                                                                                                                                                                  if(!navbar) return;

                                                                                                                                                                                                                          if(window.scrollY>60){

                                                                                                                                                                                                                                      navbar.classList.add("scrolled");

                                                                                                                                                                                                                                              }else{

                                                                                                                                                                                                                                                          navbar.classList.remove("scrolled");

                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                      });


                                                                                                                                                                                                                                                                          /* ===========================
                                                                                                                                                                                                                                                                                 BACK TO TOP
                                                                                                                                                                                                                                                                                     =========================== */

                                                                                                                                                                                                                                                                                         const backTop=document.querySelector(".back-to-top");

                                                                                                                                                                                                                                                                                             window.addEventListener("scroll",()=>{

                                                                                                                                                                                                                                                                                                     if(!backTop) return;

                                                                                                                                                                                                                                                                                                             if(window.scrollY>500){

                                                                                                                                                                                                                                                                                                                         backTop.classList.add("show");

                                                                                                                                                                                                                                                                                                                                 }else{

                                                                                                                                                                                                                                                                                                                                             backTop.classList.remove("show");

                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                         });

                                                                                                                                                                                                                                                                                                                                                             if(backTop){

                                                                                                                                                                                                                                                                                                                                                                     backTop.addEventListener("click",()=>{

                                                                                                                                                                                                                                                                                                                                                                                 window.scrollTo({

                                                                                                                                                                                                                                                                                                                                                                                                 top:0,

                                                                                                                                                                                                                                                                                                                                                                                                                 behavior:"smooth"

                                                                                                                                                                                                                                                                                                                                                                                                                             });

                                                                                                                                                                                                                                                                                                                                                                                                                                     });

                                                                                                                                                                                                                                                                                                                                                                                                                                         }


                                                                                                                                                                                                                                                                                                                                                                                                                                             /* ===========================
                                                                                                                                                                                                                                                                                                                                                                                                                                                    SCROLL REVEAL
                                                                                                                                                                                                                                                                                                                                                                                                                                                        =========================== */

                                                                                                                                                                                                                                                                                                                                                                                                                                                            const revealItems=document.querySelectorAll(".reveal");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                function revealOnScroll(){

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const trigger=window.innerHeight-120;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                revealItems.forEach(item=>{

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const top=item.getBoundingClientRect().top;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if(top<trigger){

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        item.classList.add("active");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    window.addEventListener("scroll",revealOnScroll);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        revealOnScroll();


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /* ===========================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ACTIVE NAVIGATION
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       =========================== */

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           const sections=document.querySelectorAll("section[id]");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               const navItems=document.querySelectorAll(".nav-links a");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   function activeMenu(){

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           let current="";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   sections.forEach(section=>{

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               const top=section.offsetTop-120;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           const height=section.offsetHeight;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if(pageYOffset>=top && pageYOffset<top+height){

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       current=section.getAttribute("id");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   navItems.forEach(link=>{

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               link.classList.remove("active");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           if(link.getAttribute("href")==="#"+current){

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           link.classList.add("active");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       window.addEventListener("scroll",activeMenu);


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           /* ===========================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  SMOOTH SCROLL
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      =========================== */

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          document.querySelectorAll('a[href^="#"]').forEach(anchor=>{

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  anchor.addEventListener("click",function(e){

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const target=document.querySelector(this.getAttribute("href"));

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if(target){

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          e.preventDefault();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          target.scrollIntoView({

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              behavior:"smooth",

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  block:"start"

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              /* ===========================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     HERO PARALLAX
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         =========================== */

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             const heroBg=document.querySelector(".hero-bg img, .hero-bg video");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 window.addEventListener("scroll",()=>{

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if(heroBg){

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     heroBg.style.transform=`translateY(${window.scrollY*0.25}px) scale(1.08)`;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 });


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     /* ===========================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            YEAR
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                =========================== */

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const year=document.querySelector("#year");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if(year){

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                year.textContent=new Date().getFullYear();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });